#ifndef __DO_RMAHDR_
#define __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef unsigned short US;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned RP;
typedef unsigned RO;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprChar;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef U  FlatNodeNum;
typedef U  InstNum;
typedef unsigned long long TimeStamp64;
typedef U  TimeStamp;
typedef TimeStamp  RmaTimeStamp;
typedef TimeStamp64  RmaTimeStamp64;
typedef union {
    double I633;
    unsigned long long I634;
    unsigned  I635[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
typedef struct eblk {
    struct eblk * I642;
    E_fn  I643;
    struct iptmpl * I644;
    unsigned I646;
    struct eblk * I647;
} eblk_struct;
typedef struct {
    RP  I642;
    RP  I643;
    RP  I644;
    unsigned I646;
    RP  I647;
} RmaEblk;
typedef union {
    double I633;
    unsigned long long I634;
    unsigned  I635[2];
} clock_struct;
typedef clock_struct  RmaClockStruct;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RP  I673;
    RmaEblk  I641;
    U  I674;
    US  I675 :1;
    US  I676 :4;
    US  I172 :2;
    US  state :2;
    US  I678 :1;
    US  I679 :2;
    US  I680 :2;
    US  fHsim :1;
    US  I681 :1;
    scalar  newval;
    scalar  I683;
    RP  I684;
};
typedef struct MPSched MPS;
typedef struct RmaMPSched RmaMps;
struct MPSched {
    MPS  * I663;
    scalar  I664;
    scalar  I665;
    scalar  I666;
    scalar  fHsim :1;
    scalar  I172 :6;
    U  I668;
    EBLK  I669;
    void * I670;
    UP   I671[1];
};
struct RmaMPSched {
    RP  I663;
    scalar  I664;
    scalar  I665;
    scalar  I666;
    scalar  fHsim :1;
    scalar  I172 :6;
    U  I668;
    RmaEblk  I669;
    RP  I670;
    RP   I671[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    RP  I663;
    scalar  I664;
    scalar  I665;
    scalar  I666;
    scalar  I172;
    U  I668;
    RmaEblk  I669;
    scalar  I680;
    scalar  I688;
    scalar  I689;
    scalar  I690;
    U  I691;
    RmaClockStruct  I692;
    RmaClockStruct  I693;
    U  state;
    U  I694;
    RP  I644;
    RP  I695;
    RP  I696;
    RP   I671[1];
};
typedef struct MPItem MPI;
struct MPItem {
    U  * I698;
    void * I699;
};
typedef struct {
    RmaEblk  I641;
    RP  I700;
    scalar  I701;
    scalar  I680;
    scalar  I702;
} RmaTransEventHdr;
typedef struct RmaMPSchedPulseNewCsdf RmaMpspNewCsdf;
struct RmaMPSchedPulseNewCsdf {
    RP  I663;
    scalar  I664;
    scalar  I665;
    scalar  I666;
    scalar  fHsim :1;
    scalar  I172 :6;
    U  I668;
    RmaEblk  I669;
    scalar  I680;
    scalar  I688;
    scalar  I689;
    scalar  I690;
    U  state :4;
    U  I704 :28;
    RmaClockStruct  I692;
    RmaClockStruct  I693;
    RP  I705;
    RP  I644;
    RP  I706;
    RP   I671[1];
};
typedef struct red_t {
    U  I707;
    U  I708;
    U  I709;
} RED;
typedef struct predd {
    PD_e  I172;
    RED   I710[1];
} PREDD;
typedef unsigned long long ULL;
union rhs_value {
    vec32  I711;
    scalar  I701;
    vec32  * I680;
    double I712;
    U  I713;
};
typedef struct nbs_t {
    struct nbs_t * I714;
    struct nbs_t * I716;
    void (* I717)(struct nbs_t * I718);
    unsigned I719 :1;
    unsigned I720 :1;
    unsigned I721 :1;
    unsigned I722 :1;
    unsigned I723 :27;
    void * I724;
    U  I725;
    union rhs_value I726;
    vec32  I633;
    union {
        struct nbs_t * first;
        struct nbs_t * last;
    } I728;
} NBS;
typedef struct {
    RP  I729;
    RP  I695;
    RP  I644;
    RP  I696;
    RmaEblk  I641;
    RmaEblk  I730;
    RP  I731;
    scalar  I701;
    scalar  I680;
    char state;
    uscope_t  I732;
    U  I733;
    RP  I734;
    scalar  I688;
    scalar  I689;
    scalar  I690;
    RmaClockStruct  I692;
    RmaClockStruct  I693;
    RP  I670;
} RmaPulse;
typedef struct {
    UP  I735;
    int * I736;
} MdaAndDescInfo;
struct etype {
    U  I550 :8;
    U  I551 :24;
    U  I552;
    U  I553 :1;
    U  I554 :1;
    U  I555 :1;
    U  I556 :1;
    U  I557 :1;
    U  I558 :1;
    U  I559 :1;
    U  I560 :1;
    U  I561 :1;
    U  I562 :4;
    U  I563 :1;
    U  I564 :1;
    U  I565 :1;
    U  I566 :1;
    U  I567 :1;
    U  I568 :1;
    U  I569 :1;
    U  I570 :1;
    U  I571 :1;
    U  I572 :1;
    U  I573 :2;
    U  I574 :1;
    U  I575 :2;
    U  I576 :1;
    U  I577 :1;
    U  I578 :2;
    MdaAndDescInfo  * I579;
    U  I580;
    U  I581;
    U  I582 :1;
    U  I583 :1;
    U  I584 :1;
    U  I585 :1;
    U  I586 :2;
    U  I587 :2;
    U  I588 :1;
    U  I589 :1;
    U  I590 :1;
    U  I591 :1;
    U  I592 :1;
    U  I593 :1;
    U  I594 :1;
    U  I595 :17;
};
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2,
    QIRDSpiceModuleC = 3
} QIRDModuleType;
typedef struct {
    U  I740 :1;
    U  I741 :1;
    U  I742 :1;
    U  I743 :1;
    U  I744 :1;
    U  I745 :1;
    U  I746 :1;
    U  I747 :1;
    U  I748 :1;
    U  I749 :1;
    U  I750 :1;
    U  I751 :1;
    U  I752 :1;
    U  I753 :1;
    U  I754 :1;
    U  I755 :1;
    U  I756 :1;
    U  I757 :1;
    U  I758 :1;
    U  I759 :1;
    QIRDModuleType  I760 :2;
    U  I761 :1;
    U  I762 :1;
    U  I763 :1;
    U  I764 :1;
    U  I765 :1;
    U  I766 :1;
    U  I767 :1;
    U  I768 :1;
    U  I769 :1;
    U  I770 :1;
    U  I771 :1;
    U  I772 :1;
    U  I773 :1;
    U  I774 :1;
    U  I775 :1;
    U  I776 :1;
} BitFlags;
struct qird {
    US  I4;
    US  I5;
    U  I6;
    U  I7;
    char * I8;
    char * I9;
    U  * I10;
    char * I11;
    char * I12;
    U  I13;
    U  I14;
    struct vcd_rt * I15;
    U  I17;
    struct _vcdOffset_rt * I18;
    UP  * I20;
    U  I21;
    UP  * I22;
    U  I23;
    U  I24;
    U  I25;
    U  * I26;
    U  * I27;
    void * I28;
    void * I29;
    U  I30;
    int I31;
    UP  I32;
    U  I33;
    U  I34;
    U  I35;
    UP  I36;
    U  * I37;
    BitFlags  I38;
    U  I39;
    U  I40;
    U  I41;
    U  I42;
    U  I43;
    U  * I44;
    U  I45;
    U  * I46;
    U  I47;
    U  I48;
    U  I49;
    U  I50;
    U  I51;
    U  I52;
    U  I53;
    U  * I54;
    U  * I55;
    U  I56;
    U  I57;
    U  * I58;
    U  I59;
    U  * I60;
    U  I61;
    U  I62;
    U  I63;
    U  I64;
    U  * I65;
    U  I66;
    U  * I67;
    U  I68;
    U  I69;
    U  I70;
    U  I71;
    U  I72;
    U  I73;
    U  * I74;
    char * I75;
    U  I76;
    U  I77;
    U  I78;
    U  I79;
    U  I80;
    U  * I81;
    U  I82;
    U  I83;
    UP  * I84;
    U  I85;
    U  I86;
    UP  * I87;
    U  I88;
    U  I89;
    U  I90;
    U  I91;
    U  I92;
    U  I93;
    U  * I94;
    U  I95;
    U  I96;
    U  * I97;
    U  * I98;
    U  * I99;
    U  * I100;
    U  * I101;
    U  I102;
    U  I103;
    struct taskInfo * I104;
    U  I106;
    U  I107;
    int * I108;
    UP  * I109;
    U  I110;
    U  I111;
    U  I112;
    U  I113;
    U  I114;
    struct qrefer * I115;
    U  * I117;
    unsigned * I118;
    void * I119;
    U  I120;
    U  I121;
    U  I122;
    U  I123;
    U  * I124;
    U  I125;
    U  * I126;
    U  I127;
    U  I128;
    U  I129;
    U  * I130;
    U  I131;
    U  * I132;
    U  I133;
    U  I134;
    U  * I135;
    U  I136;
    U  I137;
    U  * I138;
    U  * I139;
    U  * I140;
    U  I141;
    U  I142;
    U  I143;
    U  I144;
    U  I145;
    struct qrefee * I146;
    U  * I148;
    U  I149;
    struct qdefrefee * I150;
    U  * I152;
    int (* I153)(void);
    char * I154;
    U  I155;
    U  I156;
    void * I157;
    void * I158;
    NumLibs_t  I159;
    char * I160;
    U  * I161;
    U  I162;
    U  I163;
    U  I164;
    U  I165;
    U  I166;
    U  * I167;
    U  * I168;
    int I169;
    struct clock_load * I170;
    int I185;
    struct clock_data * I186;
    int I202;
    struct clock_hiconn * I203;
    U  I207;
    int I208;
    U  I209;
    int I210;
    U  * I211;
    U  * I212;
    U  I213;
    void * I214;
    U  I215;
    U  I216;
    UP  * I217;
    void * I218;
    U  I219;
    UP  * I220;
    U  * I221;
    int (* I222)(void);
    U  * I223;
    UP  * I224;
    U  * I225;
    U  I226 :1;
    U  I227 :31;
    U  I228;
    U  I229;
    UP  * I230;
    U  * I231;
    U  I232 :1;
    U  I233 :1;
    U  I234 :1;
    U  I235 :1;
    U  I236 :28;
    U  I237;
    U  I238;
    U  I239;
    U  I240;
    UP  * I241;
    UP  * I242;
    U  * I243;
    U  * I244;
    UP  * I245;
    UP  * I246;
    UP  * I247;
    U  * I248;
    UP  * I249;
    UP  * I250;
    UP  * I251;
    char * I252;
    U  I253;
    U  I254;
    U  I255;
    UP  * I256;
    UP  * I257;
    UP  * I258;
    UP  * I259;
    UP  * I260;
    UP  * I261;
    UP  * I262;
    UP  * I263;
    UP  * I264;
    UP  * I265;
    UP  * I266;
    UP  * I267;
    U  I268;
    U  I269;
    U  I270;
    U  I271;
    U  I272;
    U  I273;
    U  I274;
    char * I275;
    U  * I276;
    U  I277;
    U  I278;
    U  I279;
    U  I280;
    U  I281;
    U  I282;
    UP  * I283;
    UP  * I284;
    UP  * I285;
    UP  * I286;
    struct daidirInfo * I287;
    struct vcs_tftable * I289;
    U  I291;
    UP  * I292;
    UP  * I293;
    U  I294;
    U  I295;
    U  I296;
    UP  * I297;
    U  * I298;
    struct qird_hil_data * I299;
    U  * I301;
    UP  (* I302)(void);
    UP  (* I303)(void);
    UP  (* I304)(void);
    UP  (* I305)(void);
    UP  (* I306)(void);
    int * I307;
    int (* I308)(void);
    char * I309;
    UP  * I310;
    UP  * I311;
    UP  (* I312)(void);
    int (* I313)(void);
    int * I314;
    int (* I315)(void);
    int * I316;
    char * I317;
    U  * I318;
    U  * I319;
    void * I320;
    void * I321;
    U  I322;
    U  I323;
    U  I324;
    U  I325;
    U  I326;
    U  I327;
    UP  * I328;
    U  * I329;
    U  * I330;
    U  I331 :15;
    U  I332 :14;
    U  I333 :1;
    U  I334 :1;
    U  I335 :1;
    U  I336 :3;
    U  I337 :1;
    U  I338 :1;
    U  I339 :1;
    U  I340 :17;
    U  I341 :3;
    U  I342 :5;
    U  I343 :1;
    U  I344;
    struct scope * I345;
    U  I347;
    U  I348;
    U  I349;
    U  * I350;
    U  * I351;
    U  * I352;
    U  I353;
    U  I354;
    U  I355;
    struct pcbt * I356;
    U  I365;
    U  I366;
    U  I367;
    U  I368;
    void * I369;
    void * I370;
    void * I371;
    int I372;
    U  * I373;
    U  I374;
    U  I375;
    U  I376;
    U  I377;
    U  I378;
    U  I379;
    U  I380;
    void * I381;
    UP  * I382;
    U  I383;
    U  I384;
    void * I385;
    U  I386;
    void * I387;
    U  I388;
    void * I389;
    U  I390;
    int (* I391)(void);
    int (* I392)(void);
    void * I393;
    void * I394;
    void * I395;
    U  I396;
    U  I397;
    U  I398;
    U  I399;
    U  I400;
    U  I401;
    char * I402;
    U  I403;
    U  * I404;
    U  I405;
    U  * I406;
    U  I407;
    U  I408;
    U  I409;
    U  I410;
    U  I411;
    U  I412;
    U  * I413;
    U  I414;
    U  I415;
    U  * I416;
    U  I417;
    U  * I418;
    char * I419;
    U  I420;
    U  I421;
    U  I422;
    U  I423;
    U  * I424;
    U  * I425;
    U  I426;
    U  * I427;
    U  * I428;
    U  I429;
    U  I430;
    U  I431;
    U  I432;
    struct cosim_info * I433;
    U  I435;
    U  * I436;
    U  I437;
    U  I438;
    U  * I439;
    U  I440;
    U  * I441;
    U  I442;
    U  I443;
    U  * I444;
    U  I445;
    U  * I446;
    U  I447;
    U  I448;
    U  I449;
    U  I450;
    U  I451;
    U  I452;
    U  I453;
    U  I454;
    U  I455;
    U  * I456;
    U  * I457;
    void (* I458)(void);
    U  * I459;
    UP  * I460;
    struct mhdl_outInfo * I461;
    UP  * I463;
    U  I464;
    UP  * I465;
    U  I466;
    void * I467;
    U  * I468;
    void * I469;
    U  I470;
    U  I471;
    void * I472;
    void * I473;
    U  * I474;
    U  * I475;
    U  * I476;
    U  * I477;
    void * I478;
    U  I479;
    void * I480;
    U  * I481;
    char * I482;
    int (* I483)(void);
    U  * I484;
    char * I485;
    char * I486;
    U  I487;
    U  * I488;
    char * I489;
    U  I490;
    struct regInitInfo * I491;
    UP  * I493;
    U  * I494;
    char * I495;
    U  I496;
    U  I497;
    U  I498;
    U  I499;
    U  I500;
    U  I501;
    U  I502;
    U  I503;
    U  * I504;
    U  * I505;
    U  I506;
    U  I507;
    U  I508;
    U  I509;
    UP  * I510;
    U  I511;
    UP  * I512;
    U  I513;
    U  I514;
    U  I515;
    U  * I516;
    U  I517;
    U  I518;
    U  I519;
    U  * I520;
    U  * I521;
    UP  * I522;
    UP  * I523;
    void * I524;
    UP  I525;
    void * I526;
    void * I527;
    void * I528;
    void * I529;
    U  * I530;
    U  * I531;
    void * I532;
    U  I533 :1;
    U  I534 :31;
    U  I535;
    U  I536;
    int I537;
    void * I538;
    UP  * I539;
    UP  I540;
    U  I541;
    char * I542;
    U  * I543;
    U  * I544;
    char * I545;
    int * I546;
    UP  * I547;
    struct etype * I548;
    U  I596;
    U  I597;
    U  * I598;
    U  I599;
    U  * I600;
    U  I601;
    U  I602;
    U  * I603;
};
typedef struct pcbt {
    U  * I358;
    UP  I359;
    U  I360;
    U  I361;
    U  I362;
    U  I363;
    U  I364;
} PCBT;
struct iptmpl {
    QIRD  * I648;
    struct vcs_globals_t * I649;
    void * I651;
    UP  I652;
    UP  I653;
    struct iptmpl * I644[2];
};
typedef unsigned long long FileOffset;
typedef struct _hsimPeriodL {
    char  I810[256];
    struct _hsimPeriodL * I780;
} HsimPeriodL;
typedef struct {
    U   I812[2];
    U  I813 :1;
    U  I814 :1;
    U  I815 :8;
    U  I816 :8;
    U  I817 :8;
    U  I818 :4;
    unsigned long long I819;
    unsigned long long I820;
    unsigned long long I821;
    unsigned long long I822;
    unsigned long long I823;
    U  I824;
    U  I825;
    U  I826;
    U  I827;
    HsimPeriodL  * I828;
    HsimPeriodL  * I829;
    U  I830;
} HsimSignalMonitor;
typedef struct {
    FlatNodeNum  I831;
    InstNum  I832;
    U  I788;
    scalar  I833;
    UB  I834;
    UB  I835;
    UB  I836;
    U  I837;
    U  I838;
    U  I839;
    U  I840;
    U  I841;
    HsimSignalMonitor  * I842;
    RmaTimeStamp64  I843;
    U  I844;
    RmaTimeStamp64  I845;
} HsimNodeRecord;
typedef struct {
    RP  I846;
    RP  I644;
} RmaIbfIp;
typedef struct {
    RP  I846;
    RP  pcode;
} RmaIbfPcode;
typedef struct {
    RmaEblk  I641;
} RmaEvTriggeredOrSyncLoadCg;
typedef struct {
    RmaEblk  I641;
    RP  I847;
} RmaAnySchedSampleSCg;
typedef struct {
    RmaEblk  I641;
    RP  I848;
    RP  I847;
    vec32  I849;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I641;
    RP  I848;
    RP  I847;
    vec32   I679[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I641;
    RP  I848;
    RP  I847;
    scalar   I850[1];
} RmaAnySchedECg;
typedef struct {
    RP  I851;
} RmaRootCbkCg;
typedef struct {
    RP  I852;
} RmaRootVcdCg;
typedef struct {
    RP  I853;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I641;
    RP  I854;
} RmaForceCbkJmpCg;
typedef struct {
    U  I5;
    U  I637 :30;
    U  I855 :1;
    U  I856 :1;
    vec32  I711;
    U  I857;
    RP  I858;
    RP  I859;
} RmaForceSelectorV;
typedef struct {
    U  I5;
    RmaIbfPcode  I863;
} RmaNetTypeDriverGate;
typedef struct {
    U  I5;
    U  I606;
    RmaIbfPcode   I863[1];
} RmaNetTypeScatterGate;
typedef struct {
    U  I5;
    RmaIbfPcode  I863;
} RmaNetTypeGatherGate;
typedef struct {
    RmaIbfPcode  I864;
    U  I865 :3;
    U  I866 :1;
    U  I867 :1;
} RmaNbaGateOfn;
typedef struct {
    NBS  I868;
    RmaIbfPcode  I864;
} RmaNbaGate1;
typedef struct {
    RP  ptable;
    RP  pfn;
    RP  pcode;
} Rma1InputGateFaninCgS;
typedef struct {
    U  I5;
    U  iinput;
    RP  I871;
} RmaCondOptLoad;
typedef struct {
    U  I5;
    U  iinput;
    RP  I871;
} RmaMacroStateUpdate;
typedef struct {
    U  I5;
    U  state;
    U  I872;
    U  * I873;
} RmaMacroState;
typedef struct {
    U  iinput;
    RP  I874;
} RmaMultiInputLogicGateCg;
typedef struct {
    U  iinput;
    RP  ptable;
    RP  I874;
} RmaSeqPrimEdgeInputCg;
typedef struct {
    RmaEblk  I641;
    RP  pcode;
} RmaSched0GateCg;
typedef struct {
    RmaEblk  I641;
    RP  pcode;
    RP  pfn;
} RmaUdpDeltaGateCg;
typedef struct {
    RmaEblk  I641;
    RP  pcode;
    RP  pfn;
    scalar  I875;
} RmaSchedDeltaGateCg;
typedef struct {
    UB  I876;
    RP  I877;
    RP  I878;
} RmaPropNodeSeqLhsSCg;
typedef struct {
    RmaEblk  I641;
    RP  pcode;
    U  I788;
    U   I630[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I629;
    U  I879;
    U   I880[1];
} RmaDbsedRtlLoads;
typedef struct {
    U  I5;
    RP  I710;
    RmaEblk  I641;
    RmaIbfPcode  I864;
} RmaGateDelay;
typedef struct {
    U  I5;
    union {
        RP  I994;
        RP  I1228;
        RP  I1239;
    } I684;
    RmaIbfPcode  I864;
} RmaMPDelay;
typedef struct {
    U  I5;
    RmaPulse  I881;
    RmaIbfPcode  I864;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I5;
    RmaIbfPcode  I864;
    RmaMps  I882;
} RmaMPHybridDelay;
typedef struct {
    U  I5;
    U  I883;
    RmaIbfPcode  I864;
    RmaEblk  I669;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I5;
    RmaIbfPcode  I864;
    RmaMpspNewCsdf  I884;
} RmaMPPulseDelay;
typedef struct {
    U  I5;
    RmaMpsp  I884;
    RmaIbfPcode  I864;
} RmaMPPulseOptHybridDelay;
typedef struct {
    U  I5;
    U  I709;
    RmaTransEventHdr  I792;
    RP  I706;
    RmaIbfPcode  I864;
} RmaNtcTransDelay;
typedef struct {
    U  I5;
    U  I709;
    RmaEblk  I641;
    RmaIbfPcode  I864;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I641;
    RmaIbfPcode  I864;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I5;
    U  I885;
    U  I886;
    RmaTransEventHdr  I792;
    RP  I706;
    RmaIbfPcode  I864;
} RmaNtcTransDelayRF;
typedef struct {
    U  I5;
    U  I885;
    U  I886;
    RmaEblk  I641;
    RmaIbfPcode  I864;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I5;
    RP  I887;
    RmaTransEventHdr  I792;
    RP  I706;
    RmaIbfPcode  I864;
} RmaICTransDelay;
typedef struct {
    U  I5;
    RP  I887;
    RmaEblk  I641;
    RmaIbfPcode  I864;
} RmaICTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I641;
    RmaIbfPcode  I864;
} RmaICTransZeroDelay;
typedef struct {
    U  I5;
    RP  I710;
    RmaEblk  I641;
    RmaIbfPcode  I864;
} RmaICSimpleDelay;
typedef struct {
    U  I5;
    union {
        RP  psimple;
        RP  I1228;
        RP  I1239;
    } I684;
    RmaIbfPcode  I864;
} RmaICDelay;
typedef struct {
    U  I5;
    RP  I710;
    RmaEblk  I641;
    RmaIbfPcode  I864;
} RmaPortDelay;
typedef struct TableAssign_ {
    struct TableAssign_ * I780;
    struct TableAssign_ * I700;
    U  I5;
    U  iinput;
    RP  ptable;
    RP  I874;
} TableAssign;
typedef struct {
    U  I5;
    RP  I700;
    RP  I889;
} RmaTableAssignList;
typedef struct {
    RP  I890;
} RmaWakeupListCg;
typedef struct {
    U  I891;
    U  I892;
    RmaTimeStamp   I893[1];
} RmaTsArray;
typedef struct {
    U  iinput;
    RP  I894;
} RmaConditionsMdb;
typedef struct {
    RP  I780;
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
} RmaTcCoreSimple;
typedef struct {
    RP  I780;
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
    RP  I906;
} RmaTcCoreConditional;
typedef struct {
    RP  I780;
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
    RP  I906;
    RP  I907;
} RmaTcCoreConditionalOpt;
typedef struct {
    RP  I780;
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
    RP  I907;
    RP  I908;
    U  I909;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtc;
typedef struct {
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
    RP  I911;
} RmaTcCoreSimpleNoListMdb;
typedef struct {
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
    RP  I906;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
    RP  I906;
    RP  I907;
} RmaTcCoreConditionalOptNoList;
typedef struct {
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
    RP  I907;
    RP  I908;
    U  I909;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoList;
typedef struct {
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
    RP  I907;
    RP  I908;
    RP  I911;
    U  I909;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoListMdb;
typedef struct {
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
    RP  I906;
    RP  I911;
} RmaTcCoreConditionalNoListMdb;
typedef struct {
    RP  I895;
    RP  I636;
    U  I896;
    scalar  I897;
    scalar  I898;
    US  I899 :1;
    US  I900 :1;
    US  I901 :1;
    US  I902 :1;
    US  I903 :1;
    US  I904 :1;
    US  I905 :5;
    U  I912;
    RP  I913;
    RP  I914;
    RP  I906;
    RP  I915;
    RP  I916;
    RmaTimeStamp  I917;
} RmaTcCoreNochange;
typedef struct {
    RP  I918;
    RP  I780;
} RmaTcCoreNochangeList;
typedef struct {
    RP  I894;
    RmaTimeStamp  I919;
    scalar  I920;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I780;
    RP  I894;
    RmaTimeStamp  I919;
    scalar  I920;
} RmaConditionalTSLoad;
typedef struct {
    RmaTimeStamp  I919;
    scalar  I920;
    US  I897;
    RP  I907;
} RmaConditionalTSLoadOptNoList;
typedef struct {
    RP  I780;
    RmaTimeStamp  I919;
    scalar  I920;
    US  I897;
    RP  I907;
} RmaConditionalTSLoadOpt;
typedef struct {
    RP  I907;
    RP  I921;
    U  I909;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoList;
typedef struct {
    RP  I911;
    RP  I907;
    RP  I921;
    U  I909;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoListMdb;
typedef struct {
    RP  I780;
    RP  I907;
    RP  I921;
    U  I909;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtc;
typedef struct {
    U  I922;
    U  I923;
    FlatNodeNum  I924;
    U  I788;
    U  I925;
    U  I926;
    RmaIbfPcode  I864;
    union {
        scalar  I927;
        vec32  I928;
        scalar  * I929;
        vec32  * I930;
    } val;
} RmaScanSwitchData;
typedef struct {
    RP  I780;
    RP  I700;
    RP  I931;
} RmaDoublyLinkedListElem;
typedef struct {
    RP  I932;
    U  I933 :1;
    U  I934 :1;
    U  I935 :1;
    U  I936 :4;
    U  I578 :25;
    U  I937;
} RmaSwitchGateInCbkListInfo;
typedef struct {
    union {
        RmaDoublyLinkedListElem  I1271;
        RmaSwitchGateInCbkListInfo  I2;
    } I617;
    RmaIbfPcode  I864;
} RmaSwitchGate;
struct clock_load {
    U  I172 :5;
    U  I173 :12;
    U  I174 :1;
    U  I175 :2;
    U  I176 :1;
    U  I177 :1;
    U  I178 :1;
    U  I179 :9;
    U  I180;
    U  I181;
    void (* pfn)(void * I183, char val);
};
typedef struct clock_data {
    U  I188 :1;
    U  I189 :1;
    U  I190 :1;
    U  I191 :1;
    U  I172 :5;
    U  I173 :12;
    U  I192 :6;
    U  I193 :1;
    U  I175 :2;
    U  I176 :1;
    U  I179 :1;
    U  I194;
    U  I195;
    U  I196;
    U  I180;
    U  I197;
    U  I198;
    U  I199;
    U  I200;
    U  I201;
} HdbsClockData;
struct clock_hiconn {
    U  I205;
    U  I206;
    U  I180;
    U  I175;
};
typedef struct _RmaDaiCg {
    RP  I938;
    RP  I939;
    U  I940;
} RmaDaiCg;
typedef union _RmaCbkMemOptUnion {
    RP  I938;
    RP  I941;
    RP  I942;
} RmaCbkMemOptUnion;
typedef struct _RmaDaiOptCg {
    RmaCbkMemOptUnion  I943;
} RmaDaiOptCg;
struct futq {
    struct futq * I654;
    struct futq * I656;
    RmaEblk  * I657;
    RmaEblk  * I658;
    U  I646;
};
struct sched_table {
    struct futq * I659;
    struct futq I660;
    struct hash_bucket * I661;
};
struct dummyq_struct {
    clock_struct  I947;
    EBLK  * I948;
    EBLK  * I949;
    struct futq * I950;
    struct futq * I951;
    struct sched_table * I952;
    struct millenium * I954;
    EBLK  * I956;
    EBLK  * I957;
    EBLK  * I958;
    EBLK  * I959;
    EBLK  * I960;
    EBLK  * I961;
    EBLK  * I962;
    EBLK  * I963;
    EBLK  * I964;
    EBLK  * I965;
    EBLK  * I966;
    EBLK  * I967;
    EBLK  * I968;
    EBLK  * I969;
    EBLK  * I970;
    EBLK  * I971;
    EBLK  * I972;
    MPS  * I973;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef void (* FPRAP)(void *  , vec32  *  , U   );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPVU)(void *  , UB  *  , U   );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPFA)(UB  *  , UB  *  , U   , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
typedef void (* FPEVCDLSEL)(void *  , scalar   , U   , UB  *  );
typedef void (* FPEVCDLSELV)(void *  , vec32  *  , U   , U   , UB  *  );
typedef void (* FPNTYPE_L)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_H)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_HPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef struct _lqueue {
    EBLK  * I642;
    EBLK  * I974;
    int I975;
    struct _lqueue * I673;
} Queue;
typedef struct {
    EBLK  I977;
    U  I978;
    union {
        void * pHeap;
        Queue  * pList;
    } I617;
    Queue   I979[1];
} Qhdr;
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   X2val[];
extern UB   XcvtstrTR[];
extern UB   Xcvtstr[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern unsigned long long vcs_clocks;
extern UB   Xunion[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern FP   rmaFunctionArray[];
extern FP   rmaFunctionRtlArray[];
extern FP   rmaFunctionLRArray[];
extern U  rmaFunctionCount;
extern U  rmaFunctionLRCount;
extern U  rmaFunctionLRDummyCount;
extern UP  rmaFunctionDummyEndPtr;
extern UB  dummyScalar;
extern UB  fScalarIsForced;
extern UB  fScalarIsReleased;
extern U  fNotimingchecks;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedFnSamplePtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusNonCongruentFnPtr;
extern FP1  * rmaPostSchedUpdateEvTrigFnPtr;
extern FP1  * rmaSched0UpdateEvTrigFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceCbkMemoptSPostSchedCgFnPtr;
extern UB  * ptableGbl;
extern Qhdr  * lvlQueue;
extern U  mhdl_delta_count;
extern U  ignoreSchedForScanOpt;
extern U  fignoreSchedForDeadComboCloud;
extern int fZeroUser;
extern U  fEveBusPullVal;
extern U  fEveBusPullFlag;
extern UB  fNettypeIsForced;
extern UB  fNettypeIsReleased;
extern EBLK  * peblkFutQ1Head;
extern EBLK  * peblkFutQ1Tail;
extern int gFLoopDectCodeEna;
extern U  fLoopReportRT;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern UB* rmaEvalDelays(UB* pcode, scalar val);
extern UB* rmaEvalDelaysV(UB* pcode, vec32* pval);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra, U c, U w);
extern void rmaSetupRTLoopReportPtrs(UP* funcs, U cnt, U cntDummy, UP end);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlagStrengthScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlag2(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimWithFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlagFrcRel(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel2(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void VcsHsimValueChangeCB(void* pRmaDaiCg, void* pValue, unsigned int valueFormat);
extern U isNonDesignNodeCallbackList(void* pRmaDaiCg);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void VVrpNonEventNonRegdScalarForHsimOptCbkMemopt(void* ip, U nIndex);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimCbkMemOptNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchCbkMemOptForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchCbkMemOptNoDynElabS(RP* p, U val, U isStrength);
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchCbkMemOptDynElabS(U** pvcdarr, U** pcbkarr, U val, U isScalForced, U isScalReleased, U isStrength);
extern void hsimDispatchCbkMemOptNoDynElabVector(RP* /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void dumpRootVcdCg(RmaRootVcdCg* pRootVcd, scalar val);
extern void Wsvvar_callback_non_dynamic1(RP* ptr, int);
extern void rmaExecEvSyncList(RP plist);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void SchedSemiLerMPO(UB* pmpso, U partId);
extern void rmaDummyPropagate(void);
extern RP rmaTestCg(RP pcode, U vt, UB* value);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern EBLK *peblkFutQ1Head;
extern EBLK *peblkFutQ1Tail;
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0Raptor(UB *e);
extern void sched0lq(UB *e);
extern void sched0lqnc(EBLK *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void hsopt_sched0u_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, EBLK *e);
extern void sched0u(UB *e);
extern void sched0u_th(struct dummyq_struct *pq, UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, void *e, U t);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, UB *e);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void SchedSemiLerNBA(UB* peblk, U partId);
extern void NBA_Semiler(void *ip, void *pNBS);
extern void sched0sd_hsim(UB* peblk);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void schedRetainHsim(MPS* pMPS, scalar sv, scalar pv);
extern void updateRetainHsim(MPS* pMPS,scalar sv, scalar pv);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern U pvcsGetPartId();
extern void HsimPVCSPartIdCheck(U instNo);
extern void debug_func(U partId, struct dummyq_struct* pQ, EBLK* EblkLastEventx); 
extern struct dummyq_struct* pvcsGetQ(U thid);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEvent(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(RmaTimeStamp ts,RP* pdata, U fskew, U limit, U floaded, U fcondopt, RmaTimeStamp tsNochange);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern U rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWToE(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecACg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, const void*, size_t);
extern int memcmp(const void*, const void*, size_t);
extern void propagateScanOptPathVal(EBLK *peblk);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitchesV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanoptDump(UB* pcode, scalar val);
extern UB* rmaProcessScanoptDumpV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void rmaProcessPvcsCcn(UB* pcode, scalar val);
extern void rmaProcessPvcsCcnE(UB* pcode, scalar* val);
extern void rmaProcessPvcsCcnW(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnV(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnCompiledS(UB* pcode, U offset, scalar ibnval);
extern void rmaProcessPvcsCcnCompiledV(UB* pcode, U offset, vec32* pval);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);
extern UB* rmaEvalUnaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVOneFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVLargeFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalAndOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpV(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpV(UB* pcode, vec32* value);
extern UB* rmaEvalTernaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalTernaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalBinaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpS(UB* pcode, scalar val);
extern scalar rmaGetScalarFromWCg(vec32* pval, U index);
extern void rmaSetScalarInWCg(vec32* pval, U index, scalar s);
extern void rmaCountRaptorBits(void* pval, void* pvalPrev, U cbits, U vt);
extern void setHsimFunc(void* ip);
extern void unsetHsimFunc(void* ip);
extern UB* getEvcdStatusByFlagsE(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsV(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsS(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table);
extern UB* getSingleDrvEvcdStatusS(UB value, U fTBDriver);
extern UB* getSingleDrvEvcdStatusE(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusV(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getEvcdStatusByDrvEvcdStatus(UB* pdrvevcdStatus, U cdrivers, UB* table, U cbits);
extern void evcdCallback(UP pcode, U cbits);
extern UB* getSavedEvcdStatus(void);
extern void saveEvcdStatus(UB*);
extern void mhdlMarkExport(void*, U);
extern void levelInsertQueue(int);
extern void VcsRciRtl(RP pcode);
extern int gFLoopDectCodeEna;
extern U fLoopReportRT;
extern void rtSched0LoopDectDumpProcess(void* e, void* rtn, void* PQ);
extern EBLK* loopReportInlinedSched0Wrapper(EBLK *peblk);
extern void loopReportSched0Wrapper(EBLK *peblk, unsigned int sfType, unsigned int fTH, struct dummyq_struct* pq);
extern void loopReportSchedSemiLerWrapper(EBLK *peblk, int sfType);
extern void CallGraphPushNodeAndAddToGraph(UP flatNode, UP instNum, U dummy);
extern void CallGraphPopNode(void);
extern RP elabGetIpTpl(U in);
extern U rmaEvalBitBothEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQXW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval01EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval0XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval10EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval1XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX1EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX0EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitBothEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern void rmaScheduleNbaGate(RP pcode, scalar val);
extern void rmaEvaluateDynamicGateLoadsCg(RP p, scalar s);
extern void rmaEvaluateFusedWithDynamicGateLoadsCg(RP p, scalar s);
extern U rmaIsS2State(scalar s);
extern U rmaIsV2State(vec32* pval, U cbits);
extern U rmaIsW2State(vec32* pval, U cbits);
extern U rmaIsE2State(scalar* pval, U cbits);
extern void rmaUpdateRecordFor2State(HsimNodeRecord* record, U f2state);
typedef void (*FuncPtr)();
static inline U asm_bsf (U in)
{
#if defined(linux)
    U out;
    asm ("movl %1, %%eax; bsf %%eax, %%eax; movl %%eax, %0;"
        :"=r"(out)
        :"r"(in)
        :"%eax"
        );
    return out;
#else
    return 0;
#endif
}


#ifdef __cplusplus
extern "C" {
#endif
void  hsM_0_0(UB  * pcode, scalar  val);
void  hsM_0_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_0_2(UB  * pcode);
void  hsM_0_9(UB  * pcode, scalar  val);
void  hsM_1_0(UB  * pcode, scalar  val);
void  hsM_1_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_1_2(UB  * pcode);
void  hsM_1_9(UB  * pcode, scalar  val);
void  hsM_2_0(UB  * pcode, scalar  val);
void  hsM_2_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_2_2(UB  * pcode);
void  hsM_2_9(UB  * pcode, scalar  val);
void  hsM_3_0(UB  * pcode, scalar  val);
void  hsM_3_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_3_2(UB  * pcode);
void  hsM_4_0(UB  * pcode, scalar  val);
void  hsM_4_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_4_2(UB  * pcode);
void  hsM_5_0(UB  * pcode, scalar  val);
void  hsM_5_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_5_2(UB  * pcode);
void  hsM_13_0(UB  * pcode, scalar  val);
void  hsM_13_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_13_2(UB  * pcode);
void  hsM_14_0(UB  * pcode, scalar  val);
void  hsM_14_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_14_2(UB  * pcode);
void  hsM_15_0(UB  * pcode, scalar  val);
void  hsM_15_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_15_2(UB  * pcode);
void  hsM_16_0(UB  * pcode, scalar  val);
void  hsM_16_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_16_2(UB  * pcode);
void  hsM_19_0(UB  * pcode, scalar  val);
void  hsM_19_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_19_2(UB  * pcode);
void  hsM_19_11(UB  * pcode, scalar  val);
void  hsM_21_0(UB  * pcode, scalar  val);
void  hsM_21_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_21_2(UB  * pcode);
void  hsM_23_0(UB  * pcode, scalar  val);
void  hsM_23_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_23_2(UB  * pcode);
void  hsM_24_0(UB  * pcode, scalar  val);
void  hsM_24_1(UB  * pcode, scalar  val, U  I1000, scalar  * I999);
void  hsM_24_2(UB  * pcode);
void  hsM_24_11(UB  * pcode, scalar  val);
void  hsG_0(struct dummyq_struct * I986, EBLK  * I987, U  I709);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

